# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://corysullivan.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Cory Sullivan
  avatar: avatar.png
  gravatar: "183de3eaee379a59abb5d701ca2f6f91"  #Email MD5 hash
  description: "iOS Software Development" # used by search engines

  # Header and footer text
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "Sully73"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/corysullivan"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "http://stackoverflow.com/users/1615621/cory" # Full URL
  steam:
  tumblr:
  twitter: "jcsully98"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]

theme: jekyll-theme-cayman